### ISSUE TITLE
2P side portrait is not displayed on double select screen

### ISSUE THREAD

**Issue by NeatUnsou** [Windblade-GR01/Ikemen_GO#48] opened 2019-09-22 10:08 UTC
Caused by this change https://github.com/Windblade-GR01/Ikemen_GO/commit/a29b251028eb8b9643b9a694e7776da1b22a22ce

![WS000000](https://user-images.githubusercontent.com/47813229/65385639-48da8e00-dd6c-11e9-8f45-44ba9586c5ce.JPG)

**Comment by Windblade-GR01** [comment] 2019-09-22 11:23
OK, it seems that I broke it.
The problem is that if I just revert it I'll break portrait display on some screenpacks. (Like the default 1.0 one)
I'll search a way to fix both.

**Comment by Windblade-GR01** [comment] 2019-09-22 14:23
Hey NeatUnsou do you know what happens?
It's that the cell background is draw over the portraits (As the P2) so that's the reason of the bug.
You can not have a solid color portrait background or it does not display correctly.

**Comment by Windblade-GR01** [comment] 2019-09-22 14:45
So I was checking.

You know whats the problem neatunsou?
That the portrait background is drawn 2 times even when the p2 side is disabled.
And the portrait background becomes foreground.

I'll fix it ASP.

**Comment by Windblade-GR01** [comment] 2019-09-22 14:59
OK, I pushed commit c505f6f2fadf2b73f2721513c31a5096bafd1ab4
It seems that we did have the wrong view the issue was not how the table was parsed
it was how it was interpreted. 
It should be fixed now.

Tell me if you find something wrong.
I everything goes fine we could close this.

**Closed** 2019-09-25 04:12 UTC
Labels: bug
